[features]
seeds = false
skip-lint = false

[programs.devnet]
ride_payment = "3Hq1UUpj17zafnSGyVAwA2CoNGx3bLUfMXXQ9UbqEZMq"

[registry]
url = "https://api.testnet.solana.com"

[provider]
cluster = "devnet"
# wallet = "~/.config/solana/id.json"
wallet = "keys/backend_wallet.json"

[scripts]
test = "npm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "npx ts-node scripts/initialize.ts"
test_initialize_ride = "npx ts-node scripts/test_initialize_ride.ts"
test_complete_ride = "npx ts-node scripts/test_complete_ride.ts"

[test]
startup_wait = 10000
skip-deploy = true 